---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    expose: "true"
    version: "${project.version}"
    group: "io.fabric8.apps"
    expose: "true"
  name: "fabric8"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 9090
  selector:
    project: "console"
    provider: "fabric8"
    expose: "true"
    group: "io.fabric8.apps"
